FROM node:20 AS build

WORKDIR /app
COPY frontend/package*.json ./
RUN ls -al /app/package.json
RUN npm install
COPY frontend/. ./
RUN npm run build

# production env
FROM caddy:2-alpine
COPY --from=build /app/dist /usr/share/caddy
COPY caddy/static/ /usr/share/caddy
EXPOSE 80
EXPOSE 443
COPY caddy/Caddyfile.dev /etc/caddy/Caddyfile
