# GitHub actions for building and testing the backend using python 3.8 and poetry
# Based on https://jacobian.org/til/github-actions-poetry/
name: Backend CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Build CI image
        run: docker build -t nyrkio-ci -f Dockerfile.ci .
      - name: Run tests
        run: docker run --rm nyrkio-ci make test
