name: Docker Images (Staging)
on:
  #pull_request:

jobs:
  docker-images:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
          AWS_REGION: eu-north-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ENV: staging
        run: |
          # Build a docker container and push it to ECR
          echo "${{ secrets.NYRKIO_ENV_STAGING }}" > .env.backend
          docker compose -f docker-compose.yml build
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/nyrkio/staging/nginx:$IMAGE_TAG
          docker push $ECR_REGISTRY/nyrkio/staging/backend:$IMAGE_TAG
          echo "image=$ECR_REGISTRY:$IMAGE_TAG" >> $GITHUB_OUTPUT
