name: Lint

on: [pull_request]

jobs:
  lint:
    # TODO(mfleming) temporarily disable
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./backend"
          args: --exclude hunter

  format:
    # TODO(mfleming) temporarily disable
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./backend"
          args: format --exclude hunter --check
