name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build CI image
        run: docker build -t nyrkio-ci -f Dockerfile.ci .
      - name: Lint
        run: docker run --rm -v "$GITHUB_WORKSPACE:/repo" -w /repo nyrkio-ci make lint-inner

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build CI image
        run: docker build -t nyrkio-ci -f Dockerfile.ci .
      - name: Format check
        run: docker run --rm -v "$GITHUB_WORKSPACE:/repo" -w /repo nyrkio-ci make format-check-inner
