name: Performance Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  perf-tests:
    runs-on: ubuntu-latest
    environment: staging
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - name: Checkout this repo (nyrkio)
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Sync submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          git submodule status --recursive

      - name: Check out nyrkio-proprietary
        uses: actions/checkout@v6
        with:
          repository: nyrkio/nyrkio-proprietary
          path: p
          token: ${{ secrets.CHECKOUTP }}

      - name: Run lscpu
        run: lscpu -J > extra_info.json

      - name: Build CI image
        run: docker build -t nyrkio-ci -f Dockerfile.ci .

      - name: Run performance tests
        env:
          NYRKIO_ENV_TESTING: ${{ secrets.NYRKIO_ENV_TESTING }}
          NYRKIO_USERNAME: ${{ secrets.NYRKIO_USERNAME }}
          NYRKIO_PASSWORD: ${{ secrets.NYRKIO_PASSWORD }}
          # https://stackoverflow.com/a/62436027
          PULL_NUMBER: ${{ github.event.number }}
          GIT_COMMIT: ${{ github.event.pull_request.head.sha }}
          IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          export GIT_TARGET_BRANCH=${GITHUB_BASE_REF}
          echo "commit is $GIT_COMMIT"
          echo "target branch is $GIT_TARGET_BRANCH"
          echo "Running performance tests..."
          make perf
